services:
    _defaults:
        autowire: true
        autoconfigure: true

    GraffishLabs\SymfonyNatsTransport\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Tests}'
